language: python

os:
  - linux

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

addons:
  apt:
    packages:
      - flake8

install:
  - env | grep -v "encrypted" | LC_ALL=C sort
  - lscpu || sysctl hw
  - pip install brainspace gitpython numpy numpy_groupies pandas pytest
  - git config remote.origin.fetch refs/heads/*:refs/remotes/origin/*
  - git fetch origin test-data

script:
  - flake8 --select E101,E117,E125,E302,W191,W291,W293,F405,F841 .
  - python3 -c "import numpy"
  - python3 -c "import git"
  - python3 -m pytest
